name: Bitcraze website

source: src
destination: _site

permalink: /:categories/:title/
liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

relative_links:
  enabled:     true
  collections: false

keep_files: ['_site/css/kraken.css.map']

sass:
  sass_dir: _scss
  style: compressed

# Note: the ditaa and the jekyll-ditaa plugin are part of the bitcraze/web-builer
plugins:
  - jekyll-ditaa
  - jekyll-relative-links

ditaa_debug_mode: false
ditaa_output_directory: images/ditaa
